/**
 * Self-hosted, optimized assets (generated by `npm run assets` into public/assets).
 * Card images and the tub model are referenced directly in index.html so the
 * browser can discover them before any JS runs.
 */
const asset = (path) => `${import.meta.env.BASE_URL}assets/${path}`;

export const ASSETS = {
  leaves: asset('models/leaves.glb'),
  cherry: asset('models/cherry.glb'),
  blueberry: asset('models/blueberry.glb'),
  mirtiloTexture: asset('textures/pote-mirtilo.webp'),
  bubble: asset('images/bubble.webp'),
};
